name: catalyst_cardano_example
description: Demonstrates usage of catalyst_cardano plugin.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.22.1"

dependencies:
  catalyst_cardano: ^0.2.0+1
  catalyst_cardano_serialization: ^0.3.0
  catalyst_cardano_web: ^0.2.0+1
  catalyst_compression: ^0.2.0
  catalyst_compression_web: ^0.2.0
  cbor: ^6.2.0
  convert: ^3.1.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  catalyst_analysis:
    path: ../../../catalyst_analysis
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
