name: catalyst_voices_view_models
description: Catalyst Voices ViewModels.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.1"

dependencies:
  catalyst_cardano: ^0.3.0
  catalyst_cardano_serialization: ^0.4.0
  catalyst_cardano_web: ^0.3.0
  catalyst_voices_assets:
    path: ../catalyst_voices_assets
  catalyst_voices_localization:
    path: ../catalyst_voices_localization
  catalyst_voices_models:
    path: ../catalyst_voices_models
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  formz: ^0.7.0
  intl: ^0.19.0

dev_dependencies:
  catalyst_analysis: ^2.0.0
  test: ^1.24.9
