name: catalyst_voices_view_models
description: Catalyst Voices ViewModels.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.27.3"

dependencies:
  catalyst_cardano: ^0.4.1
  catalyst_cardano_serialization: ^0.5.0+4
  catalyst_cardano_web: ^0.4.0+4
  catalyst_voices_assets:
    path: ../catalyst_voices_assets
  catalyst_voices_brands:
    path: ../catalyst_voices_brands
  catalyst_voices_localization:
    path: ../catalyst_voices_localization
  catalyst_voices_models:
    path: ../catalyst_voices_models
  catalyst_voices_shared:
    path: ../catalyst_voices_shared
  email_validator: ^3.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  formz: ^0.7.0
  intl: ^0.19.0
  uuid: ^4.5.1

dev_dependencies:
  catalyst_analysis: ^2.0.1
  test: ^1.24.9
