name: catalyst_voices_view_models
description: Catalyst Voices ViewModels.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.1"

dependencies:
  catalyst_cardano: ^1.0.0
  catalyst_cardano_serialization: ^1.0.0
  catalyst_cardano_web: ^1.0.0
  catalyst_voices_assets:
    path: ../catalyst_voices_assets
  catalyst_voices_brands:
    path: ../catalyst_voices_brands
  catalyst_voices_localization:
    path: ../catalyst_voices_localization
  catalyst_voices_models:
    path: ../catalyst_voices_models
  catalyst_voices_shared:
    path: ../catalyst_voices_shared
  collection: ^1.19.1
  email_validator: ^3.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  formz: ^0.8.0
  intl: ^0.20.2
  permission_handler: ^12.0.1
  uuid_plus: ^0.1.0

dev_dependencies:
  catalyst_analysis: ^3.0.0
  flutter_test:
    sdk: flutter
  test: ^1.27.0
