name: remote_widgets
description: Catalyst remote widgets.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.1"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  rfw: ^1.0.26

dev_dependencies:
  catalyst_analysis: ^2.0.1

flutter:
  uses-material-design: true
