# cspell: words statusgossip socat

services:
  event-db:
    image: event-db:latest
    container_name: event-db
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=CatalystEventDev
      - DB_DESCRIPTION="Catalyst Event DB"
      - DB_SUPERUSER=postgres
      - DB_SUPERUSER_PASSWORD=postgres
      - DB_USER=catalyst-event-dev
      - DB_USER_PASSWORD=CHANGE_ME

      - INIT_AND_DROP_DB=true
      - WITH_MIGRATIONS=false
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  # runs old migrations for the separate `postgres` service
  # a special package for applying migrations only up to "V2_**" migrations
  event-db-v1-migrations:
    image: event-db:v1
    container_name: event-db-v1-migrations
    environment:
      - DB_HOST=event-db
      - DB_PORT=5432
      - DB_NAME=CatalystEventDev
      - DB_SUPERUSER=postgres
      - DB_SUPERUSER_PASSWORD=postgres
      - DB_USER=catalyst-event-dev
      - DB_USER_PASSWORD=CHANGE_ME

      - INIT_AND_DROP_DB=false
      - WITH_SEED_DATA=.
      - WITH_MIGRATIONS=true
    restart: "no"
    depends_on:
      event-db:
        condition: service_healthy

  # runs migrations for the separate `postgres` service
  event-db-migrations:
    image: event-db:latest
    container_name: event-db-migrations
    environment:
      - DB_HOST=event-db
      - DB_PORT=5432
      - DB_NAME=CatalystEventDev
      - DB_SUPERUSER=postgres
      - DB_SUPERUSER_PASSWORD=postgres
      - DB_USER=catalyst-event-dev
      - DB_USER_PASSWORD=CHANGE_ME

      - INIT_AND_DROP_DB=false
      - WITH_SEED_DATA=.
      - WITH_MIGRATIONS=true
    restart: "no"
    depends_on:
      event-db-v1-migrations:
        condition: service_started

  scylla-node:
    image: scylladb/scylla:latest
    container_name: scylla-node
    restart: unless-stopped
    command: --smp 2 --memory 1G --overprovisioned 1 --api-address 0.0.0.0
    ports:
      - 9042:9042
    healthcheck:
      test: cqlsh -e "SHOW VERSION" || exit 1
      interval: 15s
      timeout: 30s
      retries: 10

  cat-gateway:
    image: cat-gateway:latest
    container_name: cat-gateway
    healthcheck:
      test: "curl -s -i localhost:3030/api/v1/health/started | head -n 1 | grep 204"
      start_period: 30s
      interval: 30s
      timeout: 30s
      # approximately a 25 minutes of waiting
      retries: 50
    environment:
      - EVENT_DB_URL=postgres://catalyst-event-dev:CHANGE_ME@${EVENT_DB_URL:-event-db}/CatalystEventDev
      - CASSANDRA_PERSISTENT_URL=${INDEX_DB_URL:-scylla-node:9042}
      - CASSANDRA_VOLATILE_URL=${INDEX_DB_URL:-scylla-node:9042}
      - CHAIN_NETWORK=${ENV_TARGET:-Preprod}
      - INTERNAL_API_KEY=123
      - YES_I_REALLY_WANT_TO_PANIC=panic attack
      - SERVICE_LIVE_COUNTER_THRESHOLD=100
      - SERVICE_LIVE_TIMEOUT_INTERVAL=30
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://192.168.1.125:4317
      - OTEL_SERVICE_NAME=cat-gateway
      - RUST_LOG=info,catalyst_gateway=debug
      - TELEMETRY_ENABLED=true
      # - LOG_LEVEL=error
      # - RUST_LOG="error,cat_gateway=debug,cardano_chain_follower=debug,mithril-client=debug"
    ports:
      - 3030:3030
    depends_on:
      event-db-migrations:
        condition: service_started
      scylla-node:
        condition: service_healthy
      jaeger:
        condition: service_started
      prometheus:
        condition: service_started

  # Jaeger (visualization and storage backend)
  jaeger:
    image: jaegertracing/jaeger:2.12.0
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    volumes:
      - ./jaeger.config.yaml:/jaeger/config.yaml
    ports:
      - "16685:16685" # gRPC UI
      - "16686:16686" # Web UI
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # OTLP Metrics exporter endpoint
    command: "--config /jaeger/config.yaml"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
