name: cardano_multiplatform_lib_platform_interface
description: A common platform interface for the cardano_multiplatform_lib plugin.
repository: https://github.com/input-output-hk/catalyst-voices/tree/main/utilities/cardano_multiplatform_lib/cardano_multiplatform_lib_platform_interface
issue_tracker: https://github.com/input-output-hk/catalyst-voices/issues
topics: [blockchain, cardano, cryptocurrency, wallet]
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.19.5

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  catalyst_analysis:
    path: ../../catalyst_analysis
  flutter_test:
    sdk: flutter
