name: catalyst_voices_blocs
description: Catalyst Voices Blocs.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.1"

dependencies:
  bloc_concurrency: ^0.2.2
  catalyst_cardano: ^0.4.0+1
  catalyst_cardano_serialization: ^0.5.0+1
  catalyst_cardano_web: ^0.4.0+1
  catalyst_key_derivation: ^0.1.1
  catalyst_voices_brands:
    path: ../catalyst_voices_brands
  catalyst_voices_models:
    path: ../catalyst_voices_models
  catalyst_voices_repositories:
    path: ../catalyst_voices_repositories
  catalyst_voices_services:
    path: ../catalyst_voices_services
  catalyst_voices_shared:
    path: ../catalyst_voices_shared
  catalyst_voices_view_models:
    path: ../catalyst_voices_view_models
  collection: ^1.18.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_secure_storage: ^9.2.2
  formz: ^0.7.0
  meta: ^1.10.0
  result_type: ^0.2.0

dev_dependencies:
  bloc_test: ^9.1.4
  catalyst_analysis: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  plugin_platform_interface: ^2.1.8
  shared_preferences: ^2.3.3
  shared_preferences_platform_interface: ^2.4.1
