name: catalyst_voices_blocs
description: Catalyst Voices Blocs.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.1"

dependencies:
  bloc_concurrency: ^0.3.0
  catalyst_cardano: ^1.0.0
  catalyst_cardano_serialization: ^1.0.0
  catalyst_cardano_web: ^1.0.0
  catalyst_key_derivation: ^1.0.0
  catalyst_voices_brands:
    path: ../catalyst_voices_brands
  catalyst_voices_models:
    path: ../catalyst_voices_models
  catalyst_voices_repositories:
    path: ../catalyst_voices_repositories
  catalyst_voices_services:
    path: ../catalyst_voices_services
  catalyst_voices_shared:
    path: ../catalyst_voices_shared
  catalyst_voices_view_models:
    path: ../catalyst_voices_view_models
  collection: ^1.19.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  result_type: ^1.0.0
  rxdart: ^0.28.0
  uuid_plus: ^0.1.0

dev_dependencies:
  bloc_test: ^10.0.0
  catalyst_analysis: ^3.0.0
  catalyst_voices_dev:
    path: ../catalyst_voices_dev
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  shared_preferences: ^2.3.3
  shared_preferences_platform_interface: ^2.4.1
