name: catalyst_cose
description: A dart plugin implementing CBOR Object Signing and Encryption (RFC 9052, RFC 9053).
repository: https://github.com/input-output-hk/catalyst-voices/tree/main/catalyst_voices_packages/catalyst_cose
issue_tracker: https://github.com/input-output-hk/catalyst-voices/issues
topics: [cryptography, encryption, codec]
version: 0.2.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cbor: ^6.2.0
  convert: ^3.1.1
  cryptography: ^2.7.0

dev_dependencies:
  catalyst_analysis:
    path: ../catalyst_analysis
  test: ^1.24.9
