name: catalyst_cardano_platform_interface
description: A common platform interface for the catalyst_cardano plugin.
repository: https://github.com/input-output-hk/catalyst-voices/tree/main/catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface
issue_tracker: https://github.com/input-output-hk/catalyst-voices/issues
topics: [blockchain, cardano, cryptocurrency, wallet]
version: 0.3.0

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.1"

dependencies:
  catalyst_cardano_serialization: ^0.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  catalyst_analysis: ^2.0.0
  flutter_test:
    sdk: flutter
