name: catalyst_voices_shared
description: A Catalyst Voices Shared Package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.1"

dependencies:
  catalyst_cardano_serialization: ^0.4.0
  collection: ^1.18.0
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  intl: ^0.19.0
  logging: ^1.2.0
  web: ^1.1.0

dev_dependencies:
  catalyst_analysis: ^2.0.0
  flutter_test:
    sdk: flutter
  test: ^1.24.9
