name: catalyst_voices_shared
description: A Catalyst Voices Shared Package.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.1"

dependencies:
  catalyst_cardano_serialization: ^1.0.0
  catalyst_key_derivation: ^1.0.0
  catalyst_voices_models:
    path: ../catalyst_voices_models
  collection: ^1.19.1
  convert: ^3.1.2
  # TODO(dt-iohk): revert to pub.dev version once this is merged and released: https://github.com/emz-hanauer/dart-cryptography/pull/17
  cryptography_plus:
    git:
      url: https://github.com/emz-hanauer/dart-cryptography
      ref: 2eae39aa0f469cf065e67b760c9493b2628d3f8e
      path: cryptography/
  equatable: ^2.0.7
  fake_async: ^1.3.3
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.3.0
  sentry_flutter: ^9.6.0
  url_launcher: ^6.2.2
  uuid_plus: ^0.1.0
  web: ^1.1.1

dev_dependencies:
  catalyst_analysis: ^3.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: ^1.25.15
