name: catalyst_voices_brands
description: Catalyst Voices Brands.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.1"

dependencies:
  catalyst_voices_assets:
    path: ../catalyst_voices_assets
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  catalyst_analysis: ^2.0.0
  catalyst_voices_blocs:
    path: ../catalyst_voices_blocs
  flutter_bloc: ^8.1.5
  flutter_test:
    sdk: flutter
  test: ^1.24.9
