name: catalyst_key_derivation_platform_interface
description: A common platform interface for the catalyst_key_derivation plugin.
repository: https://github.com/input-output-hk/catalyst-voices/tree/main/catalyst_voices_packages/catalyst_key_derivation/catalyst_key_derivation_platform_interface
issue_tracker: https://github.com/input-output-hk/catalyst-voices/issues
topics: [cryptography, encryption, codec]
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.1"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  catalyst_analysis: ^2.0.0
  flutter_test:
    sdk: flutter
