name: catalyst_voices_repositories
description: Catalyst Voices Repositories.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.1"

dependencies:
  catalyst_cardano_serialization: ^0.5.0+3
  # using for document json assets
  catalyst_voices_assets:
    path: ../catalyst_voices_assets
  catalyst_voices_models:
    path: ../catalyst_voices_models
  catalyst_voices_shared:
    path: ../catalyst_voices_shared
  chopper: ^8.0.3
  collection: ^1.18.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  http: ^1.2.2
  json_annotation: ^4.8.1
  result_type: ^0.2.0
  rxdart: ^0.27.7
  synchronized: ^3.3.0+3
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.12
  catalyst_analysis: ^2.0.1
  chopper_generator: ^8.0.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  swagger_dart_code_generator: ^3.0.1