name: catalyst_voices_repositories
description: Catalyst Voices Repositories.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.1"

dependencies:
  async: ^2.13.0
  catalyst_cardano_serialization: ^1.0.0
  catalyst_compression: ^1.0.0
  catalyst_cose: ^1.0.0
  catalyst_key_derivation: ^1.0.0
  # using for document json assets
  catalyst_voices_assets:
    path: ../catalyst_voices_assets
  catalyst_voices_models:
    path: ../catalyst_voices_models
  catalyst_voices_shared:
    path: ../catalyst_voices_shared
  cbor: 6.3.7
  collection: ^1.19.1
  convert: ^3.1.2
  dio: ^5.9.0
  dio_smart_retry: ^7.0.1
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  result_type: ^1.0.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  synchronized: ^3.4.0
  uuid_plus: ^0.1.0

dev_dependencies:
  build_runner: ^2.10.3
  catalyst_analysis: ^3.0.0
  drift_dev: ^2.24.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  shared_preferences_platform_interface: ^2.4.1
  sqlite3: ^2.8.0

