name: catalyst_voices_repositories
description: Catalyst Voices Repositories.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.1"

dependencies:
  catalyst_cardano_serialization: ^0.4.0
  catalyst_voices_models:
    path: ../catalyst_voices_models
  catalyst_voices_services:
    path: ../catalyst_voices_services
  catalyst_voices_shared:
    path: ../catalyst_voices_shared
  chopper: ^7.2.0
  flutter:
    sdk: flutter
  http: ^1.2.1
  result_type: ^0.2.0
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.12
  catalyst_analysis: ^2.0.0
  mockito: ^5.4.4
  test: ^1.24.9
