name: catalyst_voices_services
description: Catalyst Voices Services.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.1"

dependencies:
  catalyst_cardano: ^0.3.0
  catalyst_cardano_serialization: ^0.4.0
  catalyst_cardano_web: ^0.3.0
  catalyst_voices_models:
    path: ../catalyst_voices_models
  catalyst_voices_repositories:
    path: ../catalyst_voices_repositories
  convert: ^3.1.1
  cryptography: ^2.7.0
  ed25519_hd_key: ^2.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  logging: ^1.2.0
  path: ^1.9.0
  rxdart: ^0.27.7
  uuid: ^4.5.1
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.12
  catalyst_analysis: ^2.0.0
  test: ^1.24.9
