name: catalyst_voices_services
description: Catalyst Voices Services.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  catalyst_cardano: ^1.0.0
  catalyst_cardano_serialization: ^1.0.0
  catalyst_cardano_web: ^1.0.0
  catalyst_key_derivation: ^1.0.0
  catalyst_voices_models:
    path: ../catalyst_voices_models
  catalyst_voices_repositories:
    path: ../catalyst_voices_repositories
  catalyst_voices_shared:
    path: ../catalyst_voices_shared
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  logging: ^1.2.0
  path: ^1.9.0
  rxdart: ^0.27.7
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
  web: ^1.1.0
  webdriver: ^3.0.3

dev_dependencies:
  catalyst_analysis: ^3.0.0
  mocktail: ^1.0.1
  shared_preferences_platform_interface: ^2.4.1
  test: ^1.24.9
