name: catalyst_voices_services
description: Catalyst Voices Services.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.1"

dependencies:
  catalyst_cardano: ^1.0.0
  catalyst_cardano_serialization: ^1.0.0
  catalyst_cardano_web: ^1.0.0
  catalyst_key_derivation: ^1.0.0
  catalyst_voices_models:
    path: ../catalyst_voices_models
  catalyst_voices_repositories:
    path: ../catalyst_voices_repositories
  catalyst_voices_shared:
    path: ../catalyst_voices_shared
  cbor: 6.3.7
  collection: ^1.19.1
  cross_file: ^0.3.4+2
  dio: ^5.9.0
  downloadsfolder: ^1.1.0
  drift: ^2.28.1
  equatable: ^2.0.7
  file_picker: ^10.3.2
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_test:
    sdk: flutter
  http: ^1.4.0
  logging: ^1.3.0
  path: ^1.9.1
  pool: ^1.5.1
  result_type: ^1.0.0
  rxdart: ^0.28.0
  sentry_dio: ^9.6.0
  sentry_drift: ^9.6.0
  sentry_flutter: ^9.6.0
  sentry_logging: ^9.6.0
  shared_preferences: ^2.5.3
  synchronized: ^3.4.0
  url_launcher: ^6.3.1
  uuid_plus: ^0.1.0
  web: ^1.1.1

dev_dependencies:
  catalyst_analysis: ^3.0.0
  catalyst_compression: ^1.0.0
  mocktail: ^1.0.4
  shared_preferences_platform_interface: ^2.4.1
  test: ^1.27.0
