name: catalyst_voices_brands
description: Catalyst Voices Brands.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.1"

dependencies:
  catalyst_voices_assets:
    path: ../catalyst_voices_assets
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0

dev_dependencies:
  catalyst_analysis: ^3.0.0
  catalyst_voices_blocs:
    path: ../catalyst_voices_blocs
  flutter_test:
    sdk: flutter
  test: ^1.27.0
