name: catalyst_compression
description: A Flutter plugin exposing Brotli and zstd compression algorithms.
repository: https://github.com/input-output-hk/catalyst-voices/tree/main/catalyst_voices_packages/catalyst_compression/catalyst_compression
issue_tracker: https://github.com/input-output-hk/catalyst-voices/issues
topics: [compression, codec]
version: 0.2.0

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.22.1"

flutter:
  plugin:
    platforms:
      web:
        default_package: catalyst_compression_web

dependencies:
  catalyst_compression_platform_interface: ^0.1.1
  catalyst_compression_web: ^0.2.0
  convert: ^3.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  catalyst_analysis:
    path: ../../catalyst_analysis
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
