name: poc_local_storage
description: "A new Flutter project."
publish_to: none
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.1"

dependencies:
  collection: ^1.19.1
  file_picker: ^10.3.9
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_web_plugins:
    sdk: flutter
  go_router: ^15.1.3
  pointycastle: ^3.0.0

dev_dependencies:
  catalyst_analysis: ^3.0.0

flutter:
  uses-material-design: true
