name: poc_local_storage
description: "A new Flutter project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.27.3"

dependencies:
  collection: ^1.19.0
  file_picker: ^8.0.7
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.2.3
  pointycastle: ^3.9.1

dev_dependencies:
  catalyst_analysis: ^3.0.0

dependency_overrides:
  flutter_secure_storage_web: ^2.0.0-beta.1

flutter:
  uses-material-design: true
