name: catalyst_compression_platform_interface
description: A common platform interface for the catalyst_compression plugin.
repository: https://github.com/input-output-hk/catalyst-voices/tree/main/catalyst_voices_packages/catalyst_compression/catalyst_compression_platform_interface
issue_tracker: https://github.com/input-output-hk/catalyst-voices/issues
topics: [compression, codec]
version: 0.2.0

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.22.1"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  catalyst_analysis:
    path: ../../catalyst_analysis
  flutter_test:
    sdk: flutter
