# Enable unstable features:
# * imports_indent
# * imports_layout
# * imports_granularity
# * group_imports
# * reorder_impl_items
# * trailing_comma
# * where_single_line
# * wrap_comments
# * comment_width
# * blank_lines_upper_bound
# * condense_wildcard_suffixes
# * force_multiline_blocks
# * format_code_in_doc_comments
# * format_generated_files
# * hex_literal_case
# * inline_attribute_width
# * normalize_comments
# * normalize_doc_attributes
# * overflow_delimited_expr
unstable_features = true

# Compatibility:
edition = "2021"

# Tabs & spaces - Defaults, listed for clarity
tab_spaces = 4
hard_tabs = false

# Commas.
trailing_comma = "Vertical"
match_block_trailing_comma = true

# General width constraints.
max_width = 100

# Comments:
normalize_comments = true
normalize_doc_attributes = false
wrap_comments = true
comment_width = 90      # small excess is okay but prefer 80
format_code_in_doc_comments = true
format_generated_files = false

# Imports.
imports_indent = "Block"
imports_layout = "Mixed"
group_imports = "StdExternalCrate"
reorder_imports = true
imports_granularity = "Crate"

# Arguments:
use_small_heuristics = "Default"
fn_params_layout = "Compressed"
overflow_delimited_expr = true
where_single_line = true

# Misc:
inline_attribute_width = 0
blank_lines_upper_bound = 1
reorder_impl_items = true
use_field_init_shorthand = true
force_multiline_blocks = true
condense_wildcard_suffixes = true
hex_literal_case = "Upper"

# Ignored files:
ignore = []
