name: Docs

# cspell: words earthfile

on: push

concurrency:
  group: "docs"
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  ci:
    uses: input-output-hk/catalyst-ci/.github/workflows/pages.yml@v2.0.6
    with:
      aws_role_arn: arn:aws:iam::332405224602:role/ci
      aws_region: eu-central-1
      ci_cli_version: 1.3.1
      earthfile: ./docs
      target: docs
    secrets:
      earthly_runner_address: ${{ secrets.EARTHLY_SATELLITE_ADDRESS }}
      earthly_runner_secret: ${{ secrets.EARTHLY_RUNNER_SECRET }}
