name: catalyst_cardano_serialization
description: Dart package providing serialization/deserialization for common structures for Cardano blockchain.
repository: https://github.com/input-output-hk/catalyst-voices/tree/main/catalyst_voices_packages/catalyst_cardano_serialization
issue_tracker: https://github.com/input-output-hk/catalyst-voices/issues
topics: [blockchain, cardano, cryptocurrency, wallet]
version: 0.3.0

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.22.1"

dependencies:
  bech32: ^0.2.2
  bip32_ed25519: ^0.6.0
  catalyst_compression: ^0.2.0
  catalyst_compression_web: ^0.2.0
  cbor: ^6.2.0
  convert: ^3.1.1
  cryptography: ^2.7.0
  equatable: ^2.0.5
  pinenacl: ^0.6.0
  ulid: ^2.0.0

dev_dependencies:
  catalyst_analysis:
    path: ../catalyst_analysis
  test: ^1.24.9
